dist: trusty
sudo: required
language: java

jdk:
  - openjdk7
  - oraclejdk7
  
install: true

before_script:
  - git clone https://github.com/yesworkflow-org/yw-utilities.git && cd yw-utilities && mvn install && cd ..

script: mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
