version: '{build}'
os: Windows Server 2012

install:
  - cmd: choco install maven -y -f
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: git clone https://github.com/yesworkflow-org/yw-utilities.git
  - cmd: cd yw-utilities
  - cmd: mvn install
  - cmd: cd ..
  - cmd: git clone https://github.com/openskope/skope-logging-services.git
  - cmd: cd skope-logging-services
  - cmd: mvn install
  - cmd: cd ..
  - cmd: git clone https://github.com/openskope/raster-data-service.git 
  - cmd: cd raster-data-service
  - cmd: mvn install
  - cmd: cd ..
  - cmd: git clone https://github.com/openskope/static-tile-service.git
  - cmd: cd static-tile-service
  - cmd: mvn install
  - cmd: cd ..

build_script:
  - mvn clean package -DskipTest

test_script:
  - mvn cobertura:cobertura
